// シラバスデータ
// ナンバリング（授業コード）、科目名、必選区分（必修/選択必修/選択）
// category: 分類（見出しコメントとしても出力される）

const SYLLABUS_COURSES = [
  // 共通基盤ワークショップ1A
  { code: "B30A01A1", name: "共通基盤ワークショップ１Ａ　～「豊かさ」とは何だろう？～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01B1", name: "共通基盤ワークショップ１Ａ　～ＳＤＧｓから世界の問題を見つめてみよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01C1", name: "共通基盤ワークショップ１Ａ　～スポーツを創造しよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01D1", name: "共通基盤ワークショップ１Ａ　～マインドスポーツ（テーブルゲーム）の考案～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01E1", name: "共通基盤ワークショップ１Ａ　～中小企業について考えてみよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01F1", name: "共通基盤ワークショップ１Ａ　～対人関係とコミュニケーション～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01G1", name: "共通基盤ワークショップ１Ａ　～音楽文化の歴史と未来～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01H1", name: "共通基盤ワークショップ１Ａ　～自分らしくを楽しめるセルフプロデュース～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01J1", name: "共通基盤ワークショップ１Ａ　～考える力（思考力・決断力）を科学する～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01K1", name: "共通基盤ワークショップ１Ａ　～社会問題を解決に導く工学とは～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01L1", name: "共通基盤ワークショップ１Ａ　～科学技術について考えてみよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01M1", name: "共通基盤ワークショップ１Ａ　～ＡＩを使い倒してみる～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01N1", name: "共通基盤ワークショップ１Ａ　～未来の湘南工科大学をみんなで創ろう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01P1", name: "共通基盤ワークショップ１Ａ　～シミュレーションで身近な社会課題を解決～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01Q1", name: "共通基盤ワークショップ１Ａ　～湘南地域とデザイン～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },
  { code: "B30A01R1", name: "共通基盤ワークショップ１Ａ　～プラスチックについて学ぶ～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["1"], group: "workshop_1a", category: "共通基盤ワークショップ1A" },

  // 共通基盤ワークショップ1B
  { code: "B30A02A1", name: "共通基盤ワークショップ１Ｂ　～「豊かさ」とは何だろう？～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02B1", name: "共通基盤ワークショップ１Ｂ　～ＳＤＧｓから世界の問題を見つめてみよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02C1", name: "共通基盤ワークショップ１Ｂ　～スポーツを創造しよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02D1", name: "共通基盤ワークショップ１Ｂ　～マインドスポーツ（テーブルゲーム）の考案～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02E1", name: "共通基盤ワークショップ１Ｂ　～中小企業について考えてみよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02F1", name: "共通基盤ワークショップ１Ｂ　～対人関係とコミュニケーション～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02G1", name: "共通基盤ワークショップ１Ｂ　～音楽文化の歴史と未来～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02H1", name: "共通基盤ワークショップ１Ｂ　～自分らしくを楽しめるセルフプロデュース～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02J1", name: "共通基盤ワークショップ１Ｂ　～考える力（思考力・決断力）を科学する～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02K1", name: "共通基盤ワークショップ１Ｂ　～社会問題を解決に導く工学とは～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02L1", name: "共通基盤ワークショップ１Ｂ　～科学技術について考えてみよう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02M1", name: "共通基盤ワークショップ１Ｂ　～ＡＩを使い倒してみる～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02N1", name: "共通基盤ワークショップ１Ｂ　～未来の湘南工科大学をみんなで創ろう～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02P1", name: "共通基盤ワークショップ１Ｂ　～シミュレーションで身近な社会課題を解決～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02Q1", name: "共通基盤ワークショップ１Ｂ　～湘南地域とデザイン～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },
  { code: "B30A02R1", name: "共通基盤ワークショップ１Ｂ　～プラスチックについて学ぶ～", periods: [1, 2], day: "mon", type: "required", grade: [1], semester: ["2"], group: "workshop_1b", category: "共通基盤ワークショップ1B" },

  // 共通基盤ワークショップ2A
  { code: "B30B01A2", name: "共通基盤ワークショップ２Ａ　～アイデア活用演習プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01B2", name: "共通基盤ワークショップ２Ａ　～デザイン思考＠基礎プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01C2", name: "共通基盤ワークショップ２Ａ　～アイデアの作り方プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01D2", name: "共通基盤ワークショップ２Ａ　～機械創造設計製作プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01E2", name: "共通基盤ワークショップ２Ａ　～キャリアデザインプロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01F2", name: "共通基盤ワークショップ２Ａ　～アイデア発想プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01G2", name: "共通基盤ワークショップ２Ａ　～IoTファブレスへの挑戦プロジェクト(a)～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01H2", name: "共通基盤ワークショップ２Ａ　～社会人基礎力プロジェクト(a)～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01J2", name: "共通基盤ワークショップ２Ａ　～プリント回路基盤開発プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01K2", name: "共通基盤ワークショップ２Ａ　～生成AIを活用した課題解決プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01L2", name: "共通基盤ワークショップ２Ａ　～新しい数学授業を提案するプロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01M2", name: "共通基盤ワークショップ２Ａ　～Webサイト制作プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01N2", name: "共通基盤ワークショップ２Ａ　～IoTファブレスへの挑戦プロジェクト(b)～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01P2", name: "共通基盤ワークショップ２Ａ　～サイエンス教室資料作成プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01Q2", name: "共通基盤ワークショップ２Ａ　～３Ｄゲーム制作プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01R2", name: "共通基盤ワークショップ２Ａ　～プレゼンデザインプロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01S2", name: "共通基盤ワークショップ２Ａ　～地域デザインプロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01T2", name: "共通基盤ワークショップ２Ａ　～人生目標設定プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01U2", name: "共通基盤ワークショップ２Ａ　～スポーツデータサイエンスプロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },
  { code: "B30B01V2", name: "共通基盤ワークショップ２Ａ　～ことばの分析プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["1"], category: "共通基盤ワークショップ2A" },

  // 共通基盤ワークショップ2B
  { code: "B30B02A2", name: "共通基盤ワークショップ２Ｂ　～ITエンジニアの就活準備プロジェクト～", periods: [3, 4], day: "mon", type: "required", grade: [2], semester: ["2"], category: "共通基盤ワークショップ2B" },

  // 社会人基礎科目
  { code: "B30D01A1", name: "修学基礎", period: 1, day: "wed", type: "required", grade: [1], semester: ["1"], category: "社会人基礎科目" },

  // 再履修
  { code: "B30D01T2", name: "修学基礎（再）", type: "other", semester: ["1"], category: "再履修" },

  // 社会人基礎科目
  { code: "B30D02A3", name: "キャリア形成", period: 1, day: "wed", type: "required", grade: [3], semester: ["1"], category: "社会人基礎科目" },
  { code: "B30D03K3", name: "進路研究", period: 1, day: "wed", type: "required", grade: [3], semester: ["2"], category: "社会人基礎科目" },
  { code: "B30D04A1", name: "技術者倫理(坪井)", period: 3, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D04-01.html" },
  { code: "B30D04B1", name: "技術者倫理(坪井)", period: 4, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D04-01.html" },
  { code: "B30D04K1", name: "技術者倫理(坪井)", period: 1, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D04-01.html" },
  { code: "B30D04L1", name: "技術者倫理(坪井)", period: 2, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D04-01.html" },
  { code: "B30D04M1", name: "技術者倫理(武安)", period: 3, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D04-02.html" },
  { code: "B30D04N1", name: "技術者倫理(武安)", period: 4, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D04-02.html" },
  { code: "B30D05B1", name: "文章作成法", period: 4, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D05-01.html" },
  { code: "B30D05L1", name: "文章作成法", period: 4, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会人基礎科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D05-01.html" },

  // 社会貢献
  { code: "B30E08A1", name: "社会貢献活動概論", period: 3, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E08-01.html" },
  { code: "B30E08K1", name: "社会貢献活動概論", period: 2, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E08-01.html" },
  { code: "B30E09T1", name: "社会貢献活動1", type: "other", grade: [1, 2, 3, 4], semester: ["1"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E09-01.html" },
  { code: "B30E09V1", name: "社会貢献活動1", type: "other", grade: [1, 2, 3, 4], semester: ["2"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E09-01.html" },
  { code: "B30E10T2", name: "社会貢献活動2", type: "other", grade: [2, 3, 4], semester: ["1"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E10-01.html" },
  { code: "B30E10V2", name: "社会貢献活動2", type: "other", grade: [2, 3, 4], semester: ["2"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E10-01.html" },
  { code: "B30E11T2", name: "インターンシップ１", type: "other", grade: [2, 3], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E11-01.html" },
  { code: "B30E11V2", name: "インターンシップ１", type: "other", grade: [2, 3], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E11-01.html" },
  { code: "B30E12T3", name: "インターンシップ２", type: "other", grade: [3], semester: ["1"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E12-01.html" },
  { code: "B30E12V3", name: "インターンシップ２", type: "other", grade: [3], semester: ["1"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E12-01.html" },
  { code: "B30E07T2", name: "プロジェクト実習Ａ　～教職介護等体験～", type: "other", grade: [2], semester: ["1"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E07-01.html" },
  { code: "B30E07T3", name: "プロジェクト実習Ａ　～キャリアプランの作り方（入門編）～", type: "other", grade: [3], semester: ["1"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E07-03.html" },
  { code: "B30E07V2", name: "プロジェクト実習Ｂ　～教職介護等体験～", type: "other", grade: [2], semester: ["2"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E07-01.html" },
  { code: "B30E07W2", name: "プロジェクト実習Ｂ　～キャリアプランの作り方（入門編）～", type: "other", grade: [2], semester: ["2"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E07-03.html" },
  { code: "B30E07U1", name: "プロジェクト実習Ｂ　～図書館ボランティア～", type: "other", grade: [1], semester: ["2"], category: "社会貢献", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E07-02.html" },

  // 社会連携講座
  { code: "B30E01A1", name: "社会連携講座（１）～いろいろな関数～", period: 2, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E01-01.html" },
  { code: "B30E02A1", name: "社会連携講座（２）～幾何学から学ぶ～", period: 3, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E02-01.html" },
  { code: "B30E02A1", name: "社会連携講座（２）～幾何学から学ぶ～", period: 3, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E02-01.html" },
  { code: "B30E03A1", name: "社会連携講座（３）～統計学入門～", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E03-01.html" },
  { code: "B30E04B1", name: "社会連携講座（４）～教育産業概論～", period: 1, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E04-01.html" },
  { code: "B30E04B1", name: "社会連携講座（４）～教育産業概論～", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E05-01.html" },
  { code: "B30E05A1", name: "社会連携講座（５）～医療入門～", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E06-01.html" },
  { code: "B30E04B1", name: "社会連携講座（６）～思考のブラッシュアップ～", period: 2, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E06-01.html" },
  { code: "B30E04B1", name: "社会連携講座（６）～思考のブラッシュアップ～", period: 1, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E06-01.html" },
  { code: "B30E01K1", name: "社会連携講座（１）～いろいろな関数～", period: 3, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E01-01.html" },
  { code: "B30E01L1", name: "社会連携講座（１）～いろいろな関数～", period: 3, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E01-01.html" },
  { code: "B30E02K1", name: "社会連携講座（２）～幾何学から学ぶ～", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E02-01.html" },
  { code: "B30E03K1", name: "社会連携講座（３）～統計学入門～", period: 1, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E03-01.html" },
  { code: "B30E03L1", name: "社会連携講座（３）～統計学入門～", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E03-01.html" },
  { code: "B30E04K1", name: "社会連携講座（４）～教育産業概論～", period: 2, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E03-01.html" },
  { code: "B30E04L1", name: "社会連携講座（４）～教育産業概論～", period: 1, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E03-01.html" },
  { code: "B30E05K1", name: "社会連携講座（５）～医療入門～", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E06-01.html" },
  { code: "B30E06K1", name: "社会連携講座（６）～思考のブラッシュアップ～", period: 2, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "社会連携講座", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230E06-01.html" },

  // 社会関連科目
  { code: "As201Iab", name: "くらしと法", type: "elective-required", category: "社会関連科目" },
  { code: "As202Iab", name: "政治行動", type: "elective-required", category: "社会関連科目" },
  { code: "As203Iab", name: "日本国憲法", type: "elective-required", category: "社会関連科目" },
  { code: "As301Ibd", name: "国際政治経済", type: "elective-required", grade: [3, 4], category: "社会関連科目" },
  { code: "As302Ibd", name: "外交と安全保障", type: "elective-required", grade: [3, 4], category: "社会関連科目" },
  { code: "As303Ibd", name: "グローバルデータ分析", type: "elective-required", grade: [3, 4], category: "社会関連科目" },
  { code: "As304Ibd", name: "市場と経済", type: "elective-required", grade: [3, 4], category: "社会関連科目" },
  { code: "As305Ibd", name: "企業経営", type: "elective-required", grade: [3, 4], category: "社会関連科目" },
  { code: "As306Ibd", name: "会計と財務", type: "elective-required", grade: [3, 4], category: "社会関連科目" },

  // 外国語
  { code: "B30G06A2", name: "英語コミュニケーション", period: 3, day: "thu", type: "elective", grade: [2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G06-01.html" },
  { code: "B30G06K2", name: "英語コミュニケーション", period: 3, day: "thu", type: "elective", grade: [2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G06-01.html" },
  { code: "B30G01A1", name: "英語総合基礎(木3-1)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G01B1", name: "英語総合基礎(木3-2)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G01C1", name: "英語総合基礎(木3-3)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G01E1", name: "英語総合基礎(木3-4)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G01D1", name: "英語総合基礎(木4-1)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G01F1", name: "英語総合基礎(木4-2)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G01G1", name: "英語総合基礎(木4-3)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G01H1", name: "英語総合基礎(木4-4)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["1"], category: "外国語" },
  { code: "B30G02A1", name: "英語総合発展(木3-1)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G02B1", name: "英語総合発展(木3-2)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G02C1", name: "英語総合発展(木3-3)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G02D1", name: "英語総合発展(木3-4)", period: 3, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G02E1", name: "英語総合発展(木4-1)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G02F1", name: "英語総合発展(木4-2)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G02G1", name: "英語総合発展(木4-3)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G02H1", name: "英語総合発展(木4-4)", period: 4, day: "thu", type: "required", grade: [1, 2, 3], semester: ["2"], category: "外国語" },
  { code: "B30G04A1", name: "実用英語(前期)", period: 1, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G04-01.html" },
  { code: "B30G04K1", name: "実用英語(後期)", period: 1, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G04-01.html" },
  { code: "B30G07K2", name: "時事ビジネス英語", period: 1, day: "wed", type: "elective", grade: [2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G07-01.html" },
  { code: "B30G07K2", name: "時事ビジネス英語", period: 4, day: "thu", type: "elective", grade: [2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G07-01.html" },
  { code: "B30G08A1", name: "中国文化言語(2限)(前期)", period: 2, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G08-01.html" },
  { code: "B30G08B1", name: "中国文化言語(3限)(前期)", period: 3, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G08-01.html" },
  { code: "B30G08C1", name: "中国文化言語(4限)(前期)", period: 4, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G08-01.html" },
  { code: "B30G08K1", name: "中国文化言語(2限)(後期)", period: 2, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G08-01.html" },
  { code: "B30G08L1", name: "中国文化言語(3限)(後期)", period: 3, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G08-01.html" },
  { code: "B30G08M1", name: "中国文化言語(4限)(後期)", period: 4, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G08-01.html" },
  { code: "B30G09A1", name: "朝鮮文化言語(2限)(前期)", period: 2, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G09-01.html" },
  { code: "B30G09B1", name: "朝鮮文化言語(3限)(前期)", period: 3, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G09-01.html" },
  { code: "B30G09C1", name: "朝鮮文化言語(4限)(前期)", period: 4, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G09-01.html" },
  { code: "B30G09K1", name: "朝鮮文化言語(2限)(後期)", period: 2, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G09-01.html" },
  { code: "B30G09L1", name: "朝鮮文化言語(3限)(後期)", period: 3, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G09-01.html" },
  { code: "B30G09M1", name: "朝鮮文化言語(4限)(後期)", period: 4, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G09-01.html" },
  { code: "B30G03A1", name: "入門英語(前期)", period: 4, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G03-01.html" },
  { code: "B30G03K1", name: "入門英語(後期)", period: 4, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G03-01.html" },
  { code: "B30G10A1", name: "ロシア文化言語(2限)(前期)", period: 2, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G10-01.html" },
  { code: "B30G10B1", name: "ロシア文化言語(3限)(前期)", period: 3, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G10-01.html" },
  { code: "B30G10C1", name: "ロシア文化言語(4限)(前期)", period: 4, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G10-01.html" },
  { code: "B30G10K1", name: "ロシア文化言語(2限)(後期)", period: 2, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G10-01.html" },
  { code: "B30G10L1", name: "ロシア文化言語(3限)(後期)", period: 3, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G10-01.html" },
  { code: "B30G10M1", name: "ロシア文化言語(4限)(後期)", period: 4, day: "thu", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G10-01.html" },
  { code: "B30G13T2", name: "海外語学研修(前期)", type: "other", grade: [2, 3, 4], semester: ["1"], category: "外国語" },
  { code: "B30G13V2", name: "海外語学研修(後期)", type: "other", grade: [2, 3, 4], semester: ["2"], category: "外国語" },
  { code: "B30G11A1", name: "日本語Ａ(日本人履修不可)", period: 5, day: "wed", type: "elective", semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G11-01.html" },
  { code: "B30G12K1", name: "日本語Ｂ(日本人履修不可)", period: 5, day: "wed", type: "elective", semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G11-01.html" },
  { code: "B30G05A1", name: "英語資格チャレンジ", period: 1, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G05-01.html" },
  { code: "B30G05K1", name: "英語資格チャレンジ", period: 3, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "外国語", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230G05-01.html" },

  // スポーツ科目
  { code: "B30H03A1", name: "スポーツを分析する(１限目)", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "スポーツ科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230H03-02.html" },
  { code: "B30H03B1", name: "スポーツを分析する(２限目)", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "スポーツ科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230H03-01.html" },
  { code: "B30H01A2", name: "スポーツで健康を科学する(水1-1)", period: 1, day: "wed", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H01B2", name: "スポーツで健康を科学する(水1-2)", period: 1, day: "wed", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H01C2", name: "スポーツで健康を科学する(水1-3)", period: 1, day: "wed", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H01D2", name: "スポーツで健康を科学する(水2-1)", period: 2, day: "wed", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H01E2", name: "スポーツで健康を科学する(水2-2)", period: 2, day: "wed", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H01F2", name: "スポーツで健康を科学する(水2-3)", period: 2, day: "wed", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H02A2", name: "スポーツで健康を科学する(木1-1)", period: 1, day: "thu", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H02B2", name: "スポーツで健康を科学する(木1-2)", period: 1, day: "thu", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H02C2", name: "スポーツで健康を科学する(木1-3)", period: 1, day: "thu", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H02D2", name: "スポーツで健康を科学する(木2-1)", period: 2, day: "thu", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H02E2", name: "スポーツで健康を科学する(木2-2)", period: 2, day: "thu", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H02F2", name: "スポーツで健康を科学する(木2-3)", period: 2, day: "thu", type: "required", grade: [2, 3], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H01A3", name: "スポーツで健康を科学する(再)(前期)", period: 2, day: "wed", type: "other", grade: [3, 4], semester: ["1"], category: "スポーツ科目" },
  { code: "B30H01Z3", name: "スポーツで健康を科学する(再)(後期)", type: "other", grade: [3, 4], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H05A1", name: "生涯スポーツ論(前期)", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "スポーツ科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230H05-01.html" },
  { code: "B30H03K2", name: "生涯スポーツ論(後期)", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "スポーツ科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230H05-01.html" },
  { code: "B30H06U1", name: "シーズンスポーツ（サーフィン）", type: "other", category: "スポーツ科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230H06-01.html" },
  { code: "B30H02A2", name: "スポーツで健康をデザインする(水1-1)", period: 1, day: "wed", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02B2", name: "スポーツで健康をデザインする(水1-2)", period: 1, day: "wed", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02C2", name: "スポーツで健康をデザインする(水1-3)", period: 1, day: "wed", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02D2", name: "スポーツで健康をデザインする(水2-1)", period: 2, day: "wed", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02E2", name: "スポーツで健康をデザインする(水2-2)", period: 2, day: "wed", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02F2", name: "スポーツで健康をデザインする(水2-3)", period: 2, day: "wed", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02G2", name: "スポーツで健康をデザインする(木1-1)", period: 1, day: "thu", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02H2", name: "スポーツで健康をデザインする(木1-2)", period: 1, day: "thu", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02J2", name: "スポーツで健康をデザインする(木1-3)", period: 1, day: "thu", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02K2", name: "スポーツで健康をデザインする(木2-1)", period: 2, day: "thu", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02L2", name: "スポーツで健康をデザインする(木2-2)", period: 2, day: "thu", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H02M2", name: "スポーツで健康をデザインする(木2-3)", period: 2, day: "thu", type: "required", grade: [2, 3], semester: ["2"], category: "スポーツ科目" },
  { code: "B30H04K1", name: "スポーツをマネジメントする", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], category: "スポーツ科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230H04-01.html" },

  // ICT基礎
  { code: "B30I01A1", name: "コンピュータリテラシ基礎(メ)", period: 2, day: "thu", type: "required", grade: [1], semester: ["1"], category: "ICT基礎", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230I01-01.html" },
  { code: "B30I03A2", name: "コンピュータリテラシ発展 ～pythonを学ぶ～", period: 2, day: "mon", type: "elective", grade: [2, 3, 4], semester: ["1"], category: "ICT基礎", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230I03-01.html" },
  { code: "B30I03B2", name: "コンピュータリテラシ発展 ～VBAを学ぶ～", period: 1, day: "tue", type: "elective", grade: [2, 3, 4], semester: ["1"], category: "ICT基礎", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230I03-02.html" },
  { code: "B30I04K2", name: "社会とコンピュータ", period: 1, day: "mon", type: "elective", grade: [2, 3, 4], semester: ["2"], category: "ICT基礎", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230I04-01.html" },
  { code: "30I03K2", name: "コンピュータリテラシ発展 ～VBAを学ぶ～", period: 2, day: "tue", type: "elective", grade: [2, 3, 4], semester: ["2"], category: "ICT基礎", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230I03-02.html" },
  { code: "B30I30L2", name: "コンピュータリテラシ発展 ～pythonを学ぶ～", period: 2, day: "wed", type: "elective", grade: [2, 3, 4], semester: ["2"], category: "ICT基礎", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230I03-01.html" },
  { code: "B30I02K1", name: "コンピュータリテラシ応用(メ)", period: 2, day: "thu", type: "required", grade: [1], semester: ["2"], category: "ICT基礎", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230I02-01.html" },

  // 教職科目
  { code: "Z30W15A4", name: "（教）教育実習ゼミ2", period: 3, day: "mon", type: "required", grade: [4], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W15-01.html" },
  { code: "Z30W08A3", name: "（教）教育課程論", period: 5, day: "mon", type: "required", grade: [3], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W08-01.html" },
  { code: "Z30W12A3", name: "（教）道徳教育の指導法", period: 2, day: "tue", type: "required", grade: [3], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W12-01.html" },
  { code: "Z30W25A3", name: "（教）数学科教材研究1", period: 3, day: "tue", type: "required", grade: [3], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W25-01.html" },
  { code: "Z30W03A1", name: "（教）教育原理", period: 5, day: "tue", type: "required", grade: [1], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W03-01.html" },
  { code: "Z30W29A2", name: "（教）情報科教育法1", period: 5, day: "tue", type: "required", grade: [2], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W29-01.html" },
  { code: "Z30W25B3", name: "（教）数学科教材研究1", period: 5, day: "tue", type: "required", grade: [3], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W25-01.html" },
  { code: "Z30W05A2", name: "（教）特別支援教育", period: 2, day: "wed", type: "required", grade: [2], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W05-01.html" },
  { code: "Z30W15B4", name: "（教）教育実習ゼミ2", period: 2, day: "wed", type: "required", grade: [4], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W17-01.html" },
  { code: "Z30W23A2", name: "（教）数学科教育法1", period: 3, day: "wed", type: "required", grade: [2], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W23-01.html" },
  { code: "Z30W02A1", name: "（教）教育心理", period: 5, day: "thu", type: "required", grade: [1], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W02-01.html" },
  { code: "Z30W11A3", name: "（教）教育関係法規", period: 5, day: "thu", type: "elective", grade: [3], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W11-01.html" },
  { code: "Z30W10A3", name: "（教）教育相談", period: 2, day: "fri", type: "required", grade: [3], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W10-01.html" },
  { code: "Z30W07T3", name: "（教）学校インターンシップ", type: "elective", grade: [3], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W07-01.html" },
  { code: "Z30W16T4", name: "（教）教育実習1", type: "required", grade: [4], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W16-01.html" },
  { code: "Z30W17T4", name: "（教）教育実習2", type: "required", grade: [4], semester: ["1"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W17-01.html" },
  { code: "Z30W14K3", name: "（教）教育実習ゼミ1", period: 5, day: "mon", type: "required", grade: [3], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W14-01.html" },
  { code: "Z30W09K3", name: "（教）特別活動及び総合的な学習の指導法", period: 2, day: "tue", type: "required", grade: [3], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W09-01.html" },
  { code: "Z30W26K3", name: "（教）数学科教材研究2", period: 3, day: "tue", type: "required", grade: [3], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W26-01.html" },
  { code: "Z30W18K4", name: "（教）教職基礎演習(中・高)", period: 3, day: "tue", type: "required", grade: [4], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W18-01.html" },
  { code: "Z30W01K1", name: "（教）教職入門", period: 5, day: "tue", type: "required", grade: [1], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W01-01.html" },
  { code: "Z30W30K2", name: "（教）情報科教育法2", period: 5, day: "tue", type: "required", grade: [2], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W30-01.html" },
  { code: "Z30W26L3", name: "（教）数学科教材研究2", period: 5, day: "tue", type: "required", grade: [3], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W26-01.html" },
  { code: "Z30W06K2", name: "（教）教育制度論", period: 2, day: "wed", type: "required", grade: [2], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W06-01.html" },
  { code: "Z30W14L3", name: "（教）教育実習ゼミ1", period: 2, day: "wed", type: "required", grade: [3], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W14-01.html" },
  { code: "Z30W24K2", name: "（教）数学科教育法2", period: 4, day: "wed", type: "required", grade: [2], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W24-01.html" },
  { code: "Z30W04K1", name: "（教）教育方法（ＩＣＴの活用を含む）", period: 5, day: "thu", type: "required", grade: [1], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W04-01.html" },
  { code: "Z30W13K3", name: "（教）生徒指導及び進路指導", period: 5, day: "fri", type: "required", grade: [3], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W13-01.html" },
  { code: "Z30W07V2", name: "（教）学校インターンシップ", type: "elective", grade: [2], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W07-01.html" },
  { code: "Z30W16V4", name: "（教）教育実習1", type: "required", grade: [4], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W16-01.html" },
  { code: "Z30W17V4", name: "（教）教育実習2", type: "required", grade: [4], semester: ["2"], category: "教職科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-Z230W17-01.html" },

  // 情報学科専門科目
  { code: "B31P04A2", name: "アルゴリズムとデータ構造実習(堀越)", periods: [1, 2], day: "mon", type: "elective-required", grade: [2, 3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P04B2", name: "アルゴリズムとデータ構造実習(川上)", periods: [1, 2], day: "mon", type: "elective-required", grade: [2, 3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N06A2", name: "離散数学", period: 1, day: "mon", type: "elective", grade: [2, 3, 4], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N06-01.html" },
  { code: "B31Q17A3", name: "サウンドエンジニアリング", period: 1, day: "mon", type: "elective", grade: [3, 4], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q17-01.html" },
  { code: "B31P08B3", name: "コンピュータアーキテクチャ", period: 2, day: "mon", type: "elective-required", grade: [3, 4], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N19A3", name: "代数学", period: 2, day: "mon", type: "elective", grade: [3, 4], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N19-01.html" },
  { code: "B31Q17B3", name: "サウンドエンジニアリング", period: 2, day: "mon", type: "elective", grade: [3, 4], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q17-01.html" },
  { code: "B31Q18A3", name: "コンピュータビジョン", period: 2, day: "mon", type: "elective-required", grade: [3, 4], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L03A1", name: "プログラミング基礎(メ)", period: 3, day: "mon", type: "required", grade: [1], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P12A3", name: "通信プログラミング実習", periods: [3, 4], day: "mon", type: "elective", grade: [3], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P12-01.html" },
  { code: "B31Q24A3", name: "認知情報学実習", periods: [3, 4], day: "mon", type: "elective-required", grade: [3, 4], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P10A3", name: "情報理論", period: 3, day: "mon", type: "elective-required", grade: [3, 4], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N18A3", name: "数値計算プログラミング(メ)", period: 4, day: "mon", type: "elective", grade: [3, 4], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N18-01.html" },
  { code: "B31P08A3", name: "コンピュータアーキテクチャ", period: 4, day: "mon", type: "elective-required", semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q07A2", name: "Web入門(メ)", period: 5, day: "mon", type: "elective", grade: [1], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q07-01.html" },
  { code: "B31L02A1", name: "データサイエンス入門1(メ)", period: 1, day: "tue", type: "required", grade: [1], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P03C2", name: "ネットワークアーキテクチャ", period: 1, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31R05A2", name: "プレゼンテーションスキル", period: 1, day: "tue", type: "elective", grade: [2], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231R05-01.html" },
  { code: "B31P03A3", name: "コンパイラ(梅澤・鈴木)", period: 1, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P09B3", name: "コンパイラ(鈴木・梅澤)", period: 1, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q10A2", name: "コンテンツ制作", periods: [1, 2], day: "tue", type: "elective-required", grade: [2, 3, 4], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L01A1", name: "コンピュータシステム入門(メ)", period: 2, day: "tue", type: "required", grade: [1], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N05A2", name: "データサイエンス実践(鈴木)", period: 2, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N05B2", name: "データサイエンス実践(浅野)", period: 2, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q09A2", name: "コミュニケーション工学", period: 2, day: "tue", type: "elective", grade: [2], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q09-01.html" },
  { code: "B31P10B3", name: "情報理論", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q09A2", name: "暗号とセキュリティ", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L04A1", name: "プログラミングのための基礎数学(メ)", period: 3, day: "tue", type: "required", grade: [1], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P02A2", name: "論理回路(二宮)", period: 3, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P02B2", name: "論理回路(浅野)", period: 3, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P03A2", name: "ネットワークアーキテクチャ(三浦)", period: 3, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q08A2", name: "Webデザイン", period: 3, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q21A3", name: "メディアインタラクション(堀越)", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q21B3", name: "メディアインタラクション(山崎)", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q26A3", name: "テキストマイニング", period: 3, day: "tue", type: "elective", grade: [3], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q26-01.html" },
  { code: "B31N01A1", name: "確率統計リテラシ1(メ)", period: 4, day: "tue", type: "elective-required", grade: [1], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N07A2", name: "プログラミングのための線形代数1", period: 4, day: "tue", type: "elective", grade: [2], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N07-01.html" },
  { code: "B31P02C2", name: "論理回路(マハブービ)", period: 4, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P03B2", name: "ネットワークアーキテクチャ(小林)", period: 4, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q08B2", name: "Webデザイン", period: 4, day: "tue", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q19A3", name: "福祉情報工学", period: 4, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31P11A3", name: "組み込みプログラミング", period: 5, day: "tue", type: "elective", grade: [3], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P11-01.html" },
  { code: "B31Q06A2", name: "デザイン思考(メ)", period: 3, day: "wed", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31R03A2", name: "金融情報処理1(メ)", period: 3, day: "wed", type: "elective", grade: [2], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231R03-01.html" },
  { code: "B31R11A3", name: "情報と職業", period: 3, day: "wed", type: "elective", grade: [3], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231R11-01.html" },
  { code: "B31N08A2", name: "プログラミングのための微分積分学1", period: 4, day: "wed", type: "elective", grade: [2], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N08-01.html" },
  { code: "B31R03B2", name: "金融情報処理1(メ)", period: 4, day: "wed", type: "elective", grade: [2], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231R03-01.html" },
  { code: "B31N09A2", name: "平面と空間の幾何学", period: 5, day: "wed", type: "elective", grade: [2], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N09-01.html" },
  { code: "B31M03A2", name: "情報学課題解決実習2A", periods: [1, 2], day: "thu", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31M03A2", name: "情報学課題解決実習2A", periods: [3, 4], day: "thu", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31M05A3", name: "情報学課題解決実習3A", periods: [1, 2], day: "thu", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31M05A3", name: "情報学課題解決実習3A", periods: [3, 4], day: "thu", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q01A1", name: "コンピュータグラフィックス入門実習(メ)", periods: [1, 2], day: "fri", type: "elective-required", grade: [1], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L08A2", name: "オブジェクト指向プログラミング実習(斎藤)(AI/CS)", periods: [1, 2], day: "fri", type: "required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L08B2", name: "オブジェクト指向プログラミング実習(松田)(AI/CS)", periods: [1, 2], day: "fri", type: "required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L08C2", name: "オブジェクト指向プログラミング実習(山本)(AI/CS)", periods: [1, 2], day: "fri", type: "required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L08D2", name: "オブジェクト指向プログラミング実習(本多)(ISM)", periods: [1, 2], day: "fri", type: "required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L08E2", name: "オブジェクト指向プログラミング実習(川上)(ISM)", periods: [1, 2], day: "fri", type: "required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q22A3", name: "環境情報学実習", periods: [1, 2], day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q23A3", name: "教育情報システム開発実習", periods: [1, 2], day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31M01A1", name: "情報学実習A", periods: [3, 4], day: "fri", type: "required", grade: [1], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31Q10B2", name: "コンテンツ制作", periods: [3, 4], day: "fri", type: "elective-required", grade: [2], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N16A3", name: "幾何学2", period: 3, day: "fri", type: "elective", grade: [3], semester: ["1"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N16-01.html" },
  { code: "B31R09A3", name: "情報処理技術演習1(メ)", period: 3, day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31N17A3", name: "人工知能(メ)", period: 4, day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31R09B3", name: "情報処理技術演習1(メ)", period: 5, day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "情報学科専門科目" },
  { code: "B31L09K2", name: "情報倫理(メ)", period: 1, day: "mon", type: "required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q17K3", name: "サウンドエンジニアリング", period: 1, day: "mon", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q17-01.html" },
  { code: "B31N15K2", name: "幾何学1(メ)", period: 2, day: "mon", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N15-01.html" },
  { code: "B31Q20K3", name: "ゲームプログラミング", period: 2, day: "mon", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q20-01.html" },
  { code: "B31Q04K1", name: "ゲーム制作実習", periods: [3, 4], day: "mon", type: "elective-required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31N21K3", name: "人工知能実習", periods: [3, 4], day: "mon", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N21-01.html" },
  { code: "B31Q28K3", name: "インタラクション工学", period: 3, day: "mon", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q28-01.html" },
  { code: "B31Q16K2", name: "Webクライアントプログラミング(メ)", period: 5, day: "mon", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31N22K3", name: "多変量解析入門", period: 5, day: "mon", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N22-01.html" },
  { code: "B31L07K1", name: "プログラミング実習", periods: [1, 2], day: "tue", type: "required", grade: [1, 2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31N10K2", name: "ビジネスとデータサイエンス", period: 1, day: "tue", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31P06K2", name: "センシング技術", period: 1, day: "tue", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P06-01.html" },
  { code: "B31P14K3", name: "データベース実習", periods: [1, 2], day: "tue", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P14-01.html" },
  { code: "B31Q27K3", name: "企業情報マネジメント", period: 1, day: "tue", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q27-01.html" },
  { code: "B31Q29K3", name: "画像・信号処理プログラム", period: 1, day: "tue", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q29-01.html" },
  { code: "B31N10L2", name: "ビジネスとデータサイエンス", period: 2, day: "tue", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31R08K2", name: "キャリアマネジメント", period: 2, day: "tue", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231R08-01.html" },
  { code: "B31P16K3", name: "クラウドコンピューティング", period: 2, day: "tue", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P16-01.html" },
  { code: "B31N02K1", name: "確率統計リテラシ2(メ)", period: 3, day: "tue", type: "elective-required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31P07K2", name: "オペレーティングシステム実習(鈴木)", periods: [3, 4], day: "tue", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31P07L2", name: "オペレーティングシステム実習(浅野)", periods: [3, 4], day: "tue", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31N14K2", name: "データサイエンス実習", periods: [3, 4], day: "tue", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N14-01.html" },
  { code: "B31P17K3", name: "モバイルプログラミング実習", periods: [3, 4], day: "tue", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P17-01.html" },
  { code: "B31P18K3", name: "IoT実習", periods: [3, 4], day: "tue", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P18-01.html" },
  { code: "B31N03K1", name: "線形代数(メ)", period: 4, day: "tue", type: "elective-required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31R01K1", name: "IT演習基礎1(メ)", period: 4, day: "tue", type: "elective-required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q11K2", name: "映像制作", period: 4, day: "tue", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q11-01.html" },
  { code: "B31Q02K1", name: "身近なサイエンス(メ)", period: 5, day: "tue", type: "elective", grade: [1], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q02-01.html" },
  { code: "B31R01L1", name: "IT演習基礎1(メ)", period: 5, day: "tue", type: "elective-required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q03K1", name: "コンピュータグラフィックス活用実習", periods: [1, 2], day: "wed", type: "elective-required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31R06K2", name: "会計データ処理1", period: 2, day: "wed", type: "elective", grade: [2, 3, 4], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231R06-01.html" },
  { code: "B31P15K3", name: "ソフトウェア工学", period: 2, day: "wed", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231P15-01.html" },
  { code: "B31Q25K3", name: "画像・信号処理の数学", period: 2, day: "wed", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q25-01.html" },
  { code: "B31L05K1", name: "データサイエンス入門2(メ)", period: 1, day: "wed", type: "required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31N12K2", name: "プログラミングのための微分積分学2", period: 2, day: "wed", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N12-01.html" },
  { code: "B31N13K2", name: "ゲームの物理演算", period: 3, day: "wed", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N13-01.html" },
  { code: "B31R06L2", name: "会計データ処理1", period: 3, day: "wed", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231R06-01.html" },
  { code: "B31L31K3", name: "3Dモデリング実習", periods: [3, 4], day: "wed", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q31-01.html" },
  { code: "B31L06K1", name: "データサイエンスのためのプログラミング基礎(メ)", period: 4, day: "wed", type: "required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31M04K2", name: "情報学課題解決実習2B", periods: [1, 2], day: "thu", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31M04K2", name: "情報学課題解決実習2B", periods: [3, 4], day: "thu", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31M04K3", name: "情報学課題解決実習3B", periods: [1, 2], day: "thu", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231M06-01.html" },
  { code: "B31M04K3", name: "情報学課題解決実習3B", periods: [3, 4], day: "thu", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231M06-01.html" },
  { code: "B31Q05K1", name: "ヒューマンインタフェース", period: 2, day: "thu", type: "elective", grade: [1], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q05-01.html" },
  { code: "B31N04K1", name: "微分積分学(メ)", period: 1, day: "fri", type: "elective-required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31P05K2", name: "データベース(メ)", period: 1, day: "fri", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q13K2", name: "環境情報学(メ)", period: 1, day: "fri", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q14K2", name: "教育情報工学(メ)", period: 1, day: "fri", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q15K2", name: "認知情報学(メ)", period: 1, day: "fri", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q30K3", name: "3DCG実習", periods: [1, 2], day: "fri", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231Q30-01.html" },
  { code: "B31Q12K2", name: "コンピュータグラフィックス(清水・山崎)", period: 2, day: "fri", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31Q12L2", name: "コンピュータグラフィックス(山崎・清水)", period: 2, day: "fri", type: "elective-required", grade: [2], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31N20K3", name: "最適化数学", period: 2, day: "fri", type: "elective", grade: [3], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N20-01.html" },
  { code: "B31M02K1", name: "情報学実習B", periods: [3, 4], day: "fri", type: "required", grade: [1], semester: ["2"], category: "情報学科専門科目" },
  { code: "B31N11K2", name: "プログラミングのための線形代数2", period: 3, day: "fri", type: "elective", grade: [2], semester: ["2"], category: "情報学科専門科目", url: "https://syllabus.shonan-it.ac.jp/doc/S-B231N11-01.html" },

  // 人間と社会
  { code: "B30F09A3", name: "国際政治経済", period: 2, day: "mon", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F10A3", name: "外交と安全保障", period: 3, day: "mon", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F05A1", name: "物語をつくる", period: 4, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F05-01.html" },
  { code: "B30F12A1", name: "市場と経済", period: 4, day: "mon", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F01A1", name: "哲学をもつ", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F01-01.html" },
  { code: "B30F02A1", name: "心理をよむ", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F04A1", name: "歴史をみつめる", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F04-01.html" },
  { code: "B30F01B1", name: "哲学をもつ", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F01-01.html" },
  { code: "B30F02B1", name: "心理をよむ", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F10B3", name: "外交と安全保障", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F11A3", name: "グローバルデータ分析", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F14A3", name: "会計と財務", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F01C1", name: "哲学をもつ", period: 3, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F01-01.html" },
  { code: "B30F11B3", name: "グローバルデータ分析", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F13A3", name: "企業経営", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30B3", name: "会計と財務", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F07A2", name: "政治行動", period: 1, day: "wed", type: "elective-required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F08A2", name: "日本国憲法", period: 1, day: "wed", type: "elective-required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F06A2", name: "くらしと法", period: 2, day: "wed", type: "elective-required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F07B2", name: "政治行動", period: 2, day: "wed", type: "elective-required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F09B3", name: "国際政治経済", period: 2, day: "wed", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F02C1", name: "心理をよむ", period: 1, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F04B1", name: "歴史をみつめる", period: 1, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F04-01.html" },
  { code: "B30F06B2", name: "くらしと法", period: 1, day: "fri", type: "elective-required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F07C2", name: "政治行動", period: 1, day: "fri", type: "elective-required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F02D1", name: "心理をよむ", period: 2, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F03A1", name: "文化をはぐくむ", period: 2, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F03-01.html" },
  { code: "B30F04C1", name: "歴史をみつめる", period: 2, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F04-01.html" },
  { code: "B30F06C2", name: "くらしと法", period: 2, day: "fri", type: "elective-required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F07D2", name: "政治行動", period: 2, day: "fri", type: "required", grade: [2], semester: ["1"], category: "人間と社会" },
  { code: "B30F10C3", name: "外交と安全保障", period: 2, day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F03B1", name: "文化をはぐくむ", period: 3, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F03-01.html" },
  { code: "B30F12C3", name: "市場と経済", period: 3, day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F03C1", name: "文化をはぐくむ", period: 4, day: "fri", type: "elective", grade: [1, 2, 3, 4], semester: ["1"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F03-01.html" },
  { code: "B30F13B3", name: "企業経営", period: 4, day: "fri", type: "elective-required", grade: [3], semester: ["1"], category: "人間と社会" },
  { code: "B30F10K3", name: "外交と安全保障", period: 2, day: "mon", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F09K3", name: "国際政治経済", period: 3, day: "mon", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F12K3", name: "市場と経済", period: 3, day: "mon", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F05K1", name: "物語をつくる", period: 4, day: "mon", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F05-01.html" },
  { code: "B30F01K1", name: "哲学をもつ", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F01-01.html" },
  { code: "B30F02K1", name: "心理をよむ", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F04K1", name: "歴史をみつめる", period: 1, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F04-01.html" },
  { code: "B30F01L1", name: "哲学をもつ", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F01-01.html" },
  { code: "B30F02L1", name: "心理をよむ", period: 2, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F09L3", name: "国際政治経済", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F11K3", name: "グローバルデータ分析", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F14K3", name: "会計と財務", period: 2, day: "tue", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "F30F01M1", name: "哲学をもつ", period: 3, day: "tue", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F01-01.html" },
  { code: "B30F11L3", name: "グローバルデータ分析", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F13K3", name: "企業経営", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F14L3", name: "会計と財務", period: 3, day: "tue", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F13L3", name: "企業経営", period: 4, day: "tue", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F06K2", name: "くらしと法", period: 1, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F07K2", name: "政治行動", period: 1, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F06L2", name: "くらしと法", period: 2, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F07L2", name: "政治行動", period: 2, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F10L3", name: "外交と安全保障", period: 2, day: "wed", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F02M1", name: "心理をよむ", period: 1, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F04L1", name: "歴史をみつめる", period: 1, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F04-01.html" },
  { code: "B30F07M2", name: "政治行動", period: 1, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F08K2", name: "日本国憲法", period: 1, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F02N1", name: "心理をよむ", period: 2, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F02-01.html" },
  { code: "B30F03K1", name: "文化をはぐくむ", period: 2, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F03-01.html" },
  { code: "B30F04M1", name: "歴史をみつめる", period: 2, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F04-01.html" },
  { code: "B30F06M2", name: "くらしと法", period: 2, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F07N2", name: "政治行動", period: 2, day: "wed", type: "elective-required", grade: [2], semester: ["2"], category: "人間と社会" },
  { code: "B30F09M3", name: "国際政治経済", period: 2, day: "wed", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F03L1", name: "文化をはぐくむ", period: 3, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F03-01.html" },
  { code: "B30F12L3", name: "市場と経済", period: 3, day: "wed", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },
  { code: "B30F03M1", name: "文化をはぐくむ", period: 4, day: "wed", type: "elective", grade: [1, 2, 3, 4], semester: ["2"], category: "人間と社会", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230F03-01.html" },
  { code: "B30F13M3", name: "企業経営", period: 4, day: "wed", type: "elective-required", grade: [3], semester: ["2"], category: "人間と社会" },

  // 学術横断プログラム
  { code: "B30D06A2", name: "学術横断プログラム2A～AIコース～", period: 5, day: "tue", type: "elective", grade: [2], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D06-01.html" },
  { code: "B30D06C2", name: "学術横断プログラム2A～ロボティクスコース～", period: 5, day: "tue", type: "elective", grade: [2], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D06-03.html" },
  { code: "B30D06E2", name: "学術横断プログラム2A～医工学コース～", period: 5, day: "tue", type: "elective", grade: [2], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D06-05.html" },
  { code: "B30D08A3", name: "学術横断プログラム3A～AIコース～", period: 5, day: "tue", type: "elective", grade: [3], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D08-01.html" },
  { code: "B30D08C3", name: "学術横断プログラム3A～ロボティクスコース～", period: 5, day: "tue", type: "elective", grade: [3], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D08-03.html" },
  { code: "B30D08E3", name: "学術横断プログラム3A～医工学コース～", period: 5, day: "tue", type: "elective", grade: [3], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D08-05.html" },
  { code: "B30D06B2", name: "学術横断プログラム2A～IoTコース～", period: 5, day: "thu", type: "elective", grade: [2], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D06-02.html" },
  { code: "B30D06D2", name: "学術横断プログラム2A～XRメディアコース～", period: 5, day: "thu", type: "elective", grade: [2], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D06-04.html" },
  { code: "B30D08B3", name: "学術横断プログラム3A～IoTコース～", period: 5, day: "thu", type: "elective", grade: [3], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D08-02.html" },
  { code: "B30D08D3", name: "学術横断プログラム3A～XRメディアコース～", period: 5, day: "thu", type: "elective", grade: [3], semester: ["1"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D08-04.html" },
  { code: "B30D07K2", name: "学術横断プログラム2B～AIコース～", period: 5, day: "tue", type: "elective", grade: [2], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D07-01.html" },
  { code: "B30D07M2", name: "学術横断プログラム2B～ロボティクスコース～", period: 5, day: "tue", type: "elective", grade: [2], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D07-03.html" },
  { code: "B30D07P2", name: "学術横断プログラム2B～医工学コース～", period: 5, day: "tue", type: "elective", grade: [2], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D07-05.html" },
  { code: "B30D09K3", name: "学術横断プログラム3B～AIコース～", period: 5, day: "tue", type: "elective", grade: [3], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D09-01.html" },
  { code: "B30D09M3", name: "学術横断プログラム3B～ロボティクスコース～", period: 5, day: "tue", type: "elective", grade: [3], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D09-03.html" },
  { code: "B30D09P3", name: "学術横断プログラム3B～医工学コース～", period: 5, day: "tue", type: "elective", grade: [3], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D09-05.html" },
  { code: "B30D07L2", name: "学術横断プログラム2B～IoTコース～", period: 5, day: "thu", type: "elective", grade: [2], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D07-02.html" },
  { code: "B30D07N2", name: "学術横断プログラム2B～XRメディアコース～", period: 5, day: "thu", type: "elective", grade: [2], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D07-04.html" },
  { code: "B30D09L3", name: "学術横断プログラム3B～IoTコース～", period: 5, day: "thu", type: "elective", grade: [3], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D09-02.html" },
  { code: "B30D09N3", name: "学術横断プログラム3B～XRメディアコース～", period: 5, day: "thu", type: "elective", grade: [3], semester: ["2"], category: "学術横断プログラム", url: "https://syllabus.shonan-it.ac.jp/doc/S-B230D09-04.html" }
];
